# We deprecate usage of load_setup_py_data
# {% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = '0.9.10' %}

package:
  name: apodeixi
  #version: {{ data.get('version') }}
  version: {{ version }}

source:

  ##git_rev: {{ "v" + data.get('version') }}
  git_rev: v{{ version }}
  git_url: https://github.com/ChateauClaudia-Labs/apodeixi.git

requirements:
  build: # Make sure to include both what is needed to build and to run. Else will get build errors
    - python >=3.9.7
    - pandas >=1.3.4
    - openpyxl >=3.0.9
    - pyyaml >=6.0
    - xlsxwriter >=3.0.2
    - pytz ==2021.1 # Avoid version 2021.3: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - nltk ==3.6.3 # Avoid version 3.6.5: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - setuptools >=58.0.4
    - jinja2 >=2.11.3
    - wheel >=0.37.0
    - twine >=3.4.1
    - notebook >=6.4.6
    - conda-build >=3.21.7
    - toml >=0.10.2
    - click ==8.0.1 # Avoid version 8.0.3: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - tabulate >=0.8.9

  run: # Include any dependencies that the user should be prompted to also install when installing our package
    - python >=3.9.7
    - pandas >=1.3.4
    - openpyxl >=3.0.9
    - pyyaml >=6.0
    - xlsxwriter >=3.0.2
    - jinja2 >=2.11.3
    - pytz ==2021.1 # Avoid version 2021.3: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - nltk ==3.6.3 # Avoid version 3.6.5: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - notebook >=6.4.6
    - toml >=0.10.2
    - click ==8.0.1 # Avoid version 8.0.3: distribution has inconsistent Python versions in egg-info vs package's pycache, so setuptools fails when creating an Apodeixi distribution
    - tabulate >=0.8.9
    

test:
  imports: # Never leave this as "None", as build will fail (at least for default configuration)
    - unittest

about:
  home: